#!/usr/bin/env zsh
set -e -u -o pipefail


CC=${CC:-cc}
BUILD_DIR=$(mktemp -d)

function preprocess() {
	mkdir $BUILD_DIR/preprocess
	read c_file
	local preprocessed_file=${c_file%.c}.i
	local out=$BUILD_DIR/preprocess/$preprocessed_file
	$CC --preprocess $c_file -o $out
	echo $out
}

function compile-to-asm() {
	mkdir $BUILD_DIR/assembly
	read preprocessed_file
	local assembly_file=${$(basename $preprocessed_file)%.i}.S
	local out=$BUILD_DIR/assembly/$assembly_file
	cc --assemble $preprocessed_file -o $out
	echo $out
}

function assemble() {
	mkdir $BUILD_DIR/compiled
	read assembly_file
	local compiled_file=${$(basename $assembly_file)%.S}.o
	local out=$BUILD_DIR/compiled/$compiled_file
	$CC --compile $assembly_file -o $out
	echo $out
}

function link() {
	mkdir $BUILD_DIR/linked
	read compiled_file
	local linked_file=${$(basename $compiled_file)%.o}.out
	local out=$BUILD_DIR/linked/$linked_file
	if type ld64.lld > /dev/null 2>&1; then
		ld64.lld -arch arm64 -platform_version macos 14.7 14.5 \
			-L /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -lSystem \
			$compiled_file\
			-o $out
	else
		$CC $compiled_file -o $out
	fi
	echo $out
}


function main() {
	echo $@ \
		| preprocess \
		| compile-to-asm \
		| assemble \
		| link
}
main $@
